### ISSUE TITLE
Failed to start emulator., Error: 3221225477 (Windows 11)

### ISSUE THREAD

**Issue by neoacevedo** [toroxx/vscode-avdmanager#2]
When I try to launch any emulator from the virtual devices list, I get such error in vscode.

Inside the output the errors I found are:
```sh
exec: emulator.exe @flutter_emulator_android11  

Current: Fri Apr 08 2022 18:38:45 GMT-0500 (hora estándar de Colombia)

[ERR] WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
[ERR] ERROR   | Failed to open /qemu.conf, err: 2
```

**Comment by toroxx** [comment]
Since the launch AVD feature only helps to execute the emulator command.
The log messages show that the tool had run correctly.
See the line `exec: emulator.exe @flutter_emulator_android11`

But the emulator failed to start your AVD. 
It should be a config problem related to the AVD and the emulator or A bug from the android emulator.

For those [ERR] messages. I'm using Windows10, even if the emulator is started correctly (with the latest version), it still shows on the logs. So it's not so helpful.

Here are something you can try:
1. Update or Reinstall the latest emulator
2. Ensure you have installed the Android SDK Platform and System Image
3. Change AVD with another system image or API version

You can also try the below command. It will show more details and help to find out the problems.
`.\emulator.exe @flutter_emulator_android11  -verbose -show-kernel`

Hope it helps

**Comment by neoacevedo** [comment]
Mmm no, from VSCode I can launch the emulator without any issue, I mean, from the  VSCode commands I can run the emulator without problems (Flutter: Launch Emulator and select the emulator from the list) , this issue happens when I run the emulator from vscode-avdmanager. Enviado desde Correo para Windows De: Lawrence LauEnviado: sábado, 9 de abril de 2022 13:08Para: toroxx/vscode-avdmanagerCC: neoacevedo; AuthorAsunto: Re: [toroxx/vscode-avdmanager] Failed to start emulator., Error: 3221225477 (Windows 11) (Issue #2) Since the launch AVD feature only helps to execute the emulator command.The log messages show that the tool had run correctly.See the line exec: emulator.exe @flutter_emulator_android11But the emulator failed to start your AVD.It should be a config problem related to the AVD and the emulator or A bug from the android emulator.For those [ERR] messages. I'm using Windows10, even if the emulator is started correctly (with the latest version), it still shows on the logs. So it's not so helpful.Here are something you can try:Update or Reinstall the latest emulatorEnsure you have installed the Android SDK Platform and System ImageChange AVD with another system image or API versionYou can also try the below command. It will show more details and help to find out the problems..\emulator.exe @flutter_emulator_android11 -verbose -show-kernelHope it helps—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by toroxx** [comment]
Can you show more reproduction steps? Any message display?
Did you install multiple SDK cmdline-tool on your system?

Please try the below steps:
1. set `avdmanager.emulator` with absolute path of emulator.exe
   E.g. d:\dev\Android\sdk\emulator\emulator.exe 

2. set `avdmanager.emulatorOpt` to "-verbose" 
3. launch the AVD with the play button

If still fail please attach all the output from AVDmanager.  
It helps to troubleshoot this issue further,
